version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '33067:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    restart: always
  redmine:
    image: docker.io/bitnami/redmine:5
    ports:
      - '10083:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - REDMINE_SMTP_HOST=smtp.163.com
      - REDMINE_SMTP_PORT=25
      - REDMINE_SMTP_USER=kisonljs@163.com
      - REDMINE_SMTP_PASSWORD=FEYGWDPLXRPBNSBS
    restart: always

volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
